controllers:
    host: 'projet.do'
    resource: ../../src/Controller/
    type: annotation

api_auth_login:
    host: 'api.projet.do'
    path: /login_check
    methods: [POST]

api_controllers:
    host: 'api.projet.do'
    resource: ../../src/ApiController/
    type: annotation


